[package]
name = "giphy_api"
version = "0.1.0"
authors = ["HeapUnderflow <HeapUnderfl0w@users.noreply.github.com>"]

[dependencies]
reqwest = "0.6"
serde_json = "1"
serde_derive = "1"
serde = "1"

[dependencies.url]
version = "1.5"
git = "https://github.com/servo/rust-url"